// lib/tickers.js
// Searchable universe for the backtest symbol picker.
// market: "NSE" or "US".

export const TICKERS = [
  // ── NSE (Nifty 100-ish) ─────────────────────────────────────────
  { symbol: "RELIANCE",   name: "Reliance Industries",        market: "NSE" },
  { symbol: "TCS",        name: "Tata Consultancy Services",  market: "NSE" },
  { symbol: "HDFCBANK",   name: "HDFC Bank",                  market: "NSE" },
  { symbol: "INFY",       name: "Infosys",                    market: "NSE" },
  { symbol: "ICICIBANK",  name: "ICICI Bank",                 market: "NSE" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel",              market: "NSE" },
  { symbol: "SBIN",       name: "State Bank of India",        market: "NSE" },
  { symbol: "ITC",        name: "ITC",                        market: "NSE" },
  { symbol: "KOTAKBANK",  name: "Kotak Mahindra Bank",        market: "NSE" },
  { symbol: "LT",         name: "Larsen & Toubro",            market: "NSE" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever",         market: "NSE" },
  { symbol: "AXISBANK",   name: "Axis Bank",                  market: "NSE" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance",              market: "NSE" },
  { symbol: "TATAMOTORS", name: "Tata Motors",                market: "NSE" },
  { symbol: "SUNPHARMA",  name: "Sun Pharmaceutical",         market: "NSE" },
  { symbol: "MARUTI",     name: "Maruti Suzuki",              market: "NSE" },
  { symbol: "TITAN",      name: "Titan Company",              market: "NSE" },
  { symbol: "ASIANPAINT", name: "Asian Paints",               market: "NSE" },
  { symbol: "NESTLEIND",  name: "Nestle India",               market: "NSE" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement",           market: "NSE" },
  { symbol: "WIPRO",      name: "Wipro",                      market: "NSE" },
  { symbol: "HCLTECH",    name: "HCL Technologies",           market: "NSE" },
  { symbol: "ONGC",       name: "Oil & Natural Gas Corp",     market: "NSE" },
  { symbol: "NTPC",       name: "NTPC",                       market: "NSE" },
  { symbol: "POWERGRID",  name: "Power Grid Corp",            market: "NSE" },
  { symbol: "TATASTEEL",  name: "Tata Steel",                 market: "NSE" },
  { symbol: "JSWSTEEL",   name: "JSW Steel",                  market: "NSE" },
  { symbol: "COALINDIA",  name: "Coal India",                 market: "NSE" },
  { symbol: "ADANIENT",   name: "Adani Enterprises",          market: "NSE" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ",          market: "NSE" },
  { symbol: "GRASIM",     name: "Grasim Industries",          market: "NSE" },
  { symbol: "HDFCLIFE",   name: "HDFC Life Insurance",        market: "NSE" },
  { symbol: "SBILIFE",    name: "SBI Life Insurance",         market: "NSE" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv",              market: "NSE" },
  { symbol: "TECHM",      name: "Tech Mahindra",              market: "NSE" },
  { symbol: "DRREDDY",    name: "Dr. Reddy's Labs",           market: "NSE" },
  { symbol: "CIPLA",      name: "Cipla",                      market: "NSE" },
  { symbol: "DIVISLAB",   name: "Divi's Laboratories",        market: "NSE" },
  { symbol: "EICHERMOT",  name: "Eicher Motors",              market: "NSE" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp",              market: "NSE" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto",                 market: "NSE" },
  { symbol: "M&M",        name: "Mahindra & Mahindra",        market: "NSE" },
  { symbol: "BRITANNIA",  name: "Britannia Industries",       market: "NSE" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products",     market: "NSE" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank",              market: "NSE" },
  { symbol: "BPCL",       name: "Bharat Petroleum",           market: "NSE" },
  { symbol: "IOC",        name: "Indian Oil Corp",            market: "NSE" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance",            market: "NSE" },
  { symbol: "HDFCAMC",    name: "HDFC Asset Management",      market: "NSE" },
  { symbol: "DMART",      name: "Avenue Supermarts",          market: "NSE" },
  { symbol: "PIDILITIND", name: "Pidilite Industries",        market: "NSE" },
  { symbol: "DABUR",      name: "Dabur India",                market: "NSE" },
  { symbol: "GODREJCP",   name: "Godrej Consumer",            market: "NSE" },
  { symbol: "HAVELLS",    name: "Havells India",              market: "NSE" },
  { symbol: "SIEMENS",    name: "Siemens",                    market: "NSE" },
  { symbol: "DLF",        name: "DLF",                        market: "NSE" },
  { symbol: "VEDL",       name: "Vedanta",                    market: "NSE" },
  { symbol: "HINDALCO",   name: "Hindalco Industries",        market: "NSE" },
  { symbol: "IRCTC",      name: "IRCTC",                      market: "NSE" },
  { symbol: "IRFC",       name: "Indian Railway Finance",     market: "NSE" },
  { symbol: "ZOMATO",     name: "Zomato",                     market: "NSE" },
  { symbol: "PAYTM",      name: "One97 (Paytm)",              market: "NSE" },
  { symbol: "NYKAA",      name: "FSN E-Commerce (Nykaa)",     market: "NSE" },
  { symbol: "POLICYBZR",  name: "PB Fintech (Policybazaar)",  market: "NSE" },
  { symbol: "TATAPOWER",  name: "Tata Power",                 market: "NSE" },
  { symbol: "GAIL",       name: "GAIL India",                 market: "NSE" },
  { symbol: "PNB",        name: "Punjab National Bank",       market: "NSE" },
  { symbol: "BANKBARODA", name: "Bank of Baroda",             market: "NSE" },
  { symbol: "CANBK",      name: "Canara Bank",                market: "NSE" },
  { symbol: "LICI",       name: "Life Insurance Corp",        market: "NSE" },
  { symbol: "TRENT",      name: "Trent",                      market: "NSE" },
  { symbol: "NAUKRI",     name: "Info Edge",                  market: "NSE" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals",           market: "NSE" },
  { symbol: "AMBUJACEM",  name: "Ambuja Cements",             market: "NSE" },
  { symbol: "BEL",        name: "Bharat Electronics",         market: "NSE" },
  { symbol: "HAL",        name: "Hindustan Aeronautics",      market: "NSE" },
  { symbol: "BOSCHLTD",   name: "Bosch",                      market: "NSE" },

  // ── US (large & popular) ────────────────────────────────────────
  { symbol: "AAPL",  name: "Apple",                    market: "US" },
  { symbol: "MSFT",  name: "Microsoft",                market: "US" },
  { symbol: "GOOGL", name: "Alphabet (Class A)",       market: "US" },
  { symbol: "GOOG",  name: "Alphabet (Class C)",       market: "US" },
  { symbol: "AMZN",  name: "Amazon",                   market: "US" },
  { symbol: "NVDA",  name: "NVIDIA",                   market: "US" },
  { symbol: "META",  name: "Meta Platforms",           market: "US" },
  { symbol: "TSLA",  name: "Tesla",                    market: "US" },
  { symbol: "BRK.B", name: "Berkshire Hathaway B",     market: "US" },
  { symbol: "JPM",   name: "JPMorgan Chase",           market: "US" },
  { symbol: "V",     name: "Visa",                     market: "US" },
  { symbol: "MA",    name: "Mastercard",               market: "US" },
  { symbol: "UNH",   name: "UnitedHealth Group",       market: "US" },
  { symbol: "HD",    name: "Home Depot",               market: "US" },
  { symbol: "PG",    name: "Procter & Gamble",         market: "US" },
  { symbol: "JNJ",   name: "Johnson & Johnson",        market: "US" },
  { symbol: "XOM",   name: "Exxon Mobil",              market: "US" },
  { symbol: "CVX",   name: "Chevron",                  market: "US" },
  { symbol: "COST",  name: "Costco Wholesale",         market: "US" },
  { symbol: "WMT",   name: "Walmart",                  market: "US" },
  { symbol: "KO",    name: "Coca-Cola",                market: "US" },
  { symbol: "PEP",   name: "PepsiCo",                  market: "US" },
  { symbol: "ABBV",  name: "AbbVie",                   market: "US" },
  { symbol: "MRK",   name: "Merck",                    market: "US" },
  { symbol: "LLY",   name: "Eli Lilly",                market: "US" },
  { symbol: "AVGO",  name: "Broadcom",                 market: "US" },
  { symbol: "ORCL",  name: "Oracle",                   market: "US" },
  { symbol: "CRM",   name: "Salesforce",               market: "US" },
  { symbol: "ADBE",  name: "Adobe",                    market: "US" },
  { symbol: "AMD",   name: "Advanced Micro Devices",   market: "US" },
  { symbol: "INTC",  name: "Intel",                    market: "US" },
  { symbol: "CSCO",  name: "Cisco Systems",            market: "US" },
  { symbol: "QCOM",  name: "Qualcomm",                 market: "US" },
  { symbol: "TXN",   name: "Texas Instruments",        market: "US" },
  { symbol: "NFLX",  name: "Netflix",                  market: "US" },
  { symbol: "DIS",   name: "Walt Disney",              market: "US" },
  { symbol: "BAC",   name: "Bank of America",          market: "US" },
  { symbol: "WFC",   name: "Wells Fargo",              market: "US" },
  { symbol: "GS",    name: "Goldman Sachs",            market: "US" },
  { symbol: "MS",    name: "Morgan Stanley",           market: "US" },
  { symbol: "C",     name: "Citigroup",                market: "US" },
  { symbol: "PYPL",  name: "PayPal Holdings",          market: "US" },
  { symbol: "SQ",    name: "Block",                    market: "US" },
  { symbol: "SHOP",  name: "Shopify",                  market: "US" },
  { symbol: "UBER",  name: "Uber Technologies",        market: "US" },
  { symbol: "ABNB",  name: "Airbnb",                   market: "US" },
  { symbol: "COIN",  name: "Coinbase Global",          market: "US" },
  { symbol: "PLTR",  name: "Palantir Technologies",    market: "US" },
  { symbol: "SNOW",  name: "Snowflake",                market: "US" },
  { symbol: "MU",    name: "Micron Technology",        market: "US" },
  { symbol: "BA",    name: "Boeing",                   market: "US" },
  { symbol: "CAT",   name: "Caterpillar",              market: "US" },
  { symbol: "GE",    name: "General Electric",         market: "US" },
  { symbol: "F",     name: "Ford Motor",               market: "US" },
  { symbol: "GM",    name: "General Motors",           market: "US" },
  { symbol: "NKE",   name: "Nike",                     market: "US" },
  { symbol: "SBUX",  name: "Starbucks",                market: "US" },
  { symbol: "MCD",   name: "McDonald's",               market: "US" },
  { symbol: "T",     name: "AT&T",                     market: "US" },
  { symbol: "VZ",    name: "Verizon Communications",   market: "US" },
  { symbol: "PFE",   name: "Pfizer",                   market: "US" },
  { symbol: "MRNA",  name: "Moderna",                  market: "US" },
  { symbol: "SPY",   name: "SPDR S&P 500 ETF",         market: "US" },
  { symbol: "QQQ",   name: "Invesco QQQ (Nasdaq 100)", market: "US" },
  { symbol: "DIA",   name: "SPDR Dow Jones ETF",       market: "US" },
  { symbol: "IWM",   name: "iShares Russell 2000 ETF", market: "US" },
];

// Case-insensitive search over symbol + name. Returns up to `limit` matches.
export function searchTickers(query, limit = 8) {
  const q = (query || "").trim().toUpperCase();
  if (!q) return [];
  const starts = [];
  const contains = [];
  for (const t of TICKERS) {
    const sym = t.symbol.toUpperCase();
    const name = t.name.toUpperCase();
    if (sym.startsWith(q) || name.startsWith(q)) starts.push(t);
    else if (sym.includes(q) || name.includes(q)) contains.push(t);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
